DjangoChat/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('', index, name="index"),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

chats/urls.py
from django.urls import path

from chats import views

app_name = "chats"

urlpatterns = [
    path("<int:pk>/", views.ChatDetailView.as_view(), name="chat_detail"),
    path("create_chat/", views.ChatCreateView.as_view(), name="chat_create"),
    path("delete_chat/<int:pk>/", views.ChatDeleteView.as_view(), name="chat_delete"),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("<int:pk>/", views.UserDetailView.as_view(), name="user_detail"),
    path("register/", views.UserRegisterView.as_view(), name="user_registration"),
]

chats/models.py
from django.db import models
# from users.models import MyUser
from django.conf import settings
from django.urls import reverse


class Chat(models.Model):
    creator = models.ForeignKey("users.MyUser", on_delete=models.CASCADE, related_name="chats_created")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date of chat creation")
    members = models.ManyToManyField("users.MyUser", related_name="chats_member")

    def __str__(self):
        return f"Created by {self.creator} at: {self.created_at}"

    def get_absolute_url(self):
        return reverse('chats:chat_detail', args=[self.pk])

    class Meta:
        verbose_name_plural = "Chats"


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name="messages")
    sender = models.ForeignKey("users.MyUser", on_delete=models.CASCADE, related_name="messages_sent")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date of message sent")
    text = models.TextField(verbose_name="message text")

    def __str__(self):
        return f"Sent by {self.sender} at: {self.created_at} with text: {self.text}. Chat is {self.chat}"

    class Meta:
        verbose_name_plural = "Messages"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy

from chats.models import Chat


class MyUser(AbstractUser):
    def get_chats_created(self):
        """
        :return: queryset of 'Chat' instances in which 'self' user related like 'creator'
        """
        chats = Chat.objects.filter(creator=self)
        return chats

    def get_chats_membership(self):
        """
        :return: queryset of 'Chat' instances in which 'self' user related like 'member'
        """
        chats = Chat.objects.filter(members=self)
        return chats

    def get_absolute_url(self):
        return reverse_lazy('users:user_detail', args=[self.pk])

chats/forms.py
from django import forms

from .models import Chat


class ChatCreateForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ["members",]

users/forms.py
from django.contrib.auth import forms

from users.models import MyUser

class UserCreationForm(forms.UserCreationForm):
    class Meta:
        model = MyUser
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

DjangoChat/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'chat_index.html')

chats/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, DeleteView
from django.core import serializers

from .forms import ChatCreateForm
from .models import Chat, Message


class ChatDetailView(LoginRequiredMixin, DetailView):
    model = Chat
    template_name = "chat_detail.html"
    context_object_name = "chat"
    access_denied_msg = "You are not member of this chat"

    def dispatch(self, request, *args, **kwargs):
        """
        Protect for getting access to chat_page from "not-members" of that chat
        """
        if self.kwargs["pk"] not in self.request.user.get_chats_membership().values_list("pk", flat=True):
            messages.error(request, self.access_denied_msg)
            return redirect(reverse_lazy("index"))
        else:
            return super().dispatch(request, args, kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["chat_pk"] = Chat.objects.get(pk=self.kwargs["pk"]).pk

        # context["all_messages"] = serializers.serialize("json", Message.objects.filter(chat=self.object), fields="text")
        # context["all"] = Message.objects.filter(chat=self.object).values_list("text", flat=True)

        return context


class ChatCreateView(LoginRequiredMixin, CreateView):
    model = Chat
    fields = ["members", ]
    template_name  = "chat_create.html"

    def get(self, request, *args, **kwargs):
        """
        Override for moderate queryset output in rendered form
        """
        form = ChatCreateForm()
        form.fields["members"].queryset = form.fields["members"].queryset.exclude(
            pk=self.request.user.pk
        )
        return render(self.request, self.template_name, {'form': form})

    def form_valid(self, form):
        form.instance.creator = self.request.user
        super().form_valid(form)

        chat = Chat.objects.get(pk=form.instance.pk)
        chat.members.add(self.request.user.pk)

        return HttpResponseRedirect(self.get_success_url())

    # Alternative realization
    # def form_valid(self, form):
    #     new_chat_bounded_form = form.save(commit=False)
    #     new_chat_bounded_form.creator = self.request.user
    #     super().form_valid(form)
    #
    #     chat = Chat.objects.get(pk=form.instance.pk)
    #     chat.members.add(self.request.user.pk)
    #     return HttpResponseRedirect(self.get_success_url())


class ChatDeleteView(DeleteView):
    model = Chat
    template_name = "chat_delete.html"
    success_url = reverse_lazy("index")

users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, CreateView

from users.forms import UserCreationForm
from users.models import MyUser


class UserDetailView(LoginRequiredMixin, DetailView):
    model = MyUser
    template_name = 'user_detail.html'
    context_object_name = "user"


class UserRegisterView(CreateView):
    model = MyUser
    form_class = UserCreationForm
    template_name = 'registration/user_register.html'
    context_object_name = "user"

    def get_success_url(self):
        login(self.request, user=self.object)
        return super().get_success_url()

DjangoChat/templates/base.html
{% load static %}
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}



    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.2.1/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@1.1.0-alpha/dist/chartjs-adapter-date-fns.bundle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-chart-matrix@next/dist/chartjs-chart-matrix.js"></script>

    <script>
        document.createElement('aside');
    </script>

    <style>
        aside {
            background: #f0f0f0;
            padding: 10px;
            width: 200px;
            float: right;
            }
            article {
            margin-right: 240px;
            display: block;
        }
    </style>

    <title>ChatApp</title>
</head>

<body>
<div class="container">
    {% block header %}
        <div class="row align-items-center my-5">
            <div class="col">
                <h1>
                    <a href="{% url 'index' %}">ChatApp</a>
                </h1>
            </div>
            <div class="col-auto">
                {% if user.is_authenticated %}
                    <a href="{% url 'users:user_detail' user.pk %}">{{ user.username }}'s chat rooms</a> | <a
                        href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                    <a href="{% url 'users:user_registration' %}">Register</a>
                {% endif %}
            </div>
        </div>
    {% endblock header %}

    {% block sidebar %}{% endblock sidebar %}
    {% block content %}{% endblock content %}
</div>
</body>
</html>

DjangoChat/templates/chat_index.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    {% bootstrap_messages %}

    <div class="row">
        <div class="col">
            <p>Приветствую в ChatApp by Django + Websockets</p>
        </div>
    </div>
{% endblock %}

chats/templates/chat_create.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-5">
            <form class="form-signin" method="post" action=#>
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-lg btn-primary btn-block" type="submit" value="Create">Create chat</button>
            </form>
        </div>
    </div>
{% endblock %}

chats/templates/chat_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col col-5">
            <form class="form-signing" method="post" action=#>
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-lg btn-primary btn-block" type="submit" value="Create">Delete chat</button>
            </form>
        </div>
    </div>
{% endblock %}

chats/templates/chat_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<aside>
    <div class="col">
        <p>
            Chat creator: {{ chat.creator }}
        </p>
            Chat members:
        <p></p>
            {% for member in chat.members.all%}
                <p>
                    {{ member.username }}
                </p>
            {% endfor %}
        <p>
            <a href="{% url 'chats:chat_create' %}">Create new chat</a>
        </p>
        <p>
            <a href="{% url 'chats:chat_delete' chat.pk %}">Delete this chat</a>
        </p>
    </div>
</aside>

<textarea id="chat-log" cols="50" rows="10"></textarea><br>
<input id="chat-message-input" type="text" size="50"><br>
<input id="chat-message-submit" type="button" value="Send">


{{ chat_pk|json_script:"chat_pk" }}
{{ all_messages|json_script:"all_messages" }}



<script>

    const chatNum = JSON.parse(document.getElementById("chat_pk").textContent);

    const chatSocket = new WebSocket(
        'wss://'
        + window.location.host
        + '/wss/chat/'
        + chatNum
        + '/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        document.querySelector('#chat-log').value += (data.message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));
        messageInputDom.value = '';
    };
</script>

{% endblock content %}

users/templates/user_detail.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}

<aside>
    <div class="col">
        <p>
            <a href="{% url 'chats:chat_create' %}">Create new chat</a>
        </p>
    </div>
</aside>


Chats with my participation
<p>
    {% for chat in user.get_chats_membership %}
    <p>
        <a href="{% url 'chats:chat_detail' chat.id %}">Created by {{ chat.creator.username }} at {{ chat.created_at }}</a>
    </p>
    {% endfor %}
</p>

{% endblock content %}